{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {
    "collapsed": true,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": [
    "import glob\n",
    "import urllib.request\n",
    "import sys"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true,
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 500: 'Internal Server Error'>, <traceback object at 0x7f33a409c8c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084288>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086e48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a409b488>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'View not found [name, type, prefix]: category, JPG, contentView'>, <traceback object at 0x7f33a593be08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a409c5c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4086708>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096d08>)\n",
      "Unexpected error: (<class 'ConnectionResetError'>, ConnectionResetError(104, 'Connection reset by peer'), <traceback object at 0x7f33a408e608>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40835c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f2c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081b48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408ee88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096a08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 406: 'Not Acceptable'>, <traceback object at 0x7f33a408e788>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593b2c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409c508>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4092ac8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593f608>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593fd88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408a508>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096a88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a5933948>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4083288>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083488>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593b988>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a409b5c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40997c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a407d0c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4096ec8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a40814c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40996c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4084d88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408eb08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096648>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593b348>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a6208648>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a408a548>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a4094b88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4092408>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40816c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a59569c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a409f9c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081288>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4094bc8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a6fb79c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(TimeoutError(110, 'Connection timed out'),), <traceback object at 0x7f33a4086408>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096b48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a407de08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593f248>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4092608>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096648>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a59337c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4099388>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a5931e48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4081788>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081e08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4099c48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094848>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a409c848>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4084a48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409ba08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a409cb48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081c08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4092f88>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a409f8c8>)\n",
      "Unexpected error: (<class 'ConnectionResetError'>, ConnectionResetError(104, 'Connection reset by peer'), <traceback object at 0x7f33a4083488>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593ff88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a59337c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a5933788>)\n",
      "Unexpected error: (<class 'ConnectionResetError'>, ConnectionResetError(104, 'Connection reset by peer'), <traceback object at 0x7f33a409f108>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a409f088>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084b48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096088>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(OSError(113, 'No route to host'),), <traceback object at 0x7f33a4096848>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086988>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a408a688>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408d208>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4084188>)\n",
      "Unexpected error: (<class 'UnicodeEncodeError'>, UnicodeEncodeError('ascii', 'GET /_uBgs84hCa9A/RhtL_yZI_fI/AAAAAAAAAGo/UuUanq9MDW4/s400/leon-come-tiburón-blog.jpg HTTP/1.1', 74, 75, 'ordinal not in range(128)'), <traceback object at 0x7f33a4080708>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084d48>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40a0088>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4099708>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4081588>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40813c8>)\n",
      "Unexpected error: (<class 'ConnectionResetError'>, ConnectionResetError(104, 'Connection reset by peer'), <traceback object at 0x7f33a4096b08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40964c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4099648>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083788>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a595df88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084d08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4084bc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f108>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4092fc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4081f48>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a593f308>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408e7c8>)\n",
      "Unexpected error: (<class 'UnicodeEncodeError'>, UnicodeEncodeError('ascii', 'GET /_ed_nm2jDvqQ/R0NKZf_cYDI/AAAAAAAAAFI/vog-A9fOciA/s320/Tiburón+red.jpg HTTP/1.1', 64, 65, 'ordinal not in range(128)'), <traceback object at 0x7f33a4086fc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409fe88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094548>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4099588>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593f408>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a593ba48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408a588>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408a088>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408a908>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f588>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a59314c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40811c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081708>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096748>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40963c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4096d48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 302: 'The HTTP server returned a redirect error that would lead to an infinite loop.\\nThe last 30x error message was:\\nFound'>, <traceback object at 0x7f33a593b488>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094b08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408d688>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4081088>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40817c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40928c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4092948>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a0e08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a0f08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a593f4c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a593f6c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593fa08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593f0c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408a2c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408ae08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083dc8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a4099088>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4099d08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f7c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f908>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a408a148>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408a488>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408e948>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408ed48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408efc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086688>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4086888>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4086c88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a07c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a09c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a0788>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a61fe7c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4092708>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-5, 'No address associated with hostname'),), <traceback object at 0x7f33a4094a08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40949c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081448>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081588>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(TimeoutError(110, 'Connection timed out'),), <traceback object at 0x7f33a4083608>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081788>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4092648>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(TimeoutError(110, 'Connection timed out'),), <traceback object at 0x7f33a4092fc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096dc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a5931d48>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a4083188>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 503: 'Service Unavailable'>, <traceback object at 0x7f33a4083148>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086988>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4086188>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086948>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084fc8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4084208>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084e08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a408ae88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408af08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f6c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a593b208>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 500: 'Internal Server Error'>, <traceback object at 0x7f33a408a888>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4084c08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096808>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086f88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086448>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086c48>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40a0788>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(OSError(113, 'No route to host'),), <traceback object at 0x7f33a40a05c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(TimeoutError(110, 'Connection timed out'),), <traceback object at 0x7f33a408e708>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 503: 'Service Unavailable'>, <traceback object at 0x7f33a40929c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4092e88>)\n",
      "Unexpected error: (<class 'ConnectionResetError'>, ConnectionResetError(104, 'Connection reset by peer'), <traceback object at 0x7f33a4092748>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408da08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a408dc48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408d608>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083b48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083ec8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593b288>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(TimeoutError(110, 'Connection timed out'),), <traceback object at 0x7f33a40a0448>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(TimeoutError(110, 'Connection timed out'),), <traceback object at 0x7f33a40a07c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086f88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086288>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a595de88>)\n",
      "Unexpected error: (<class 'IsADirectoryError'>, IsADirectoryError(21, 'Is a directory'), <traceback object at 0x7f33a61f7048>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096fc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096e88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a59314c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a4092e08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4084f88>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4084dc8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4084508>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593f888>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408d5c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081c08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40819c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081408>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081088>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083ac8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4083848>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094448>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593b588>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096308>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086d48>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40861c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408e6c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40841c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(TimeoutError(110, 'Connection timed out'),), <traceback object at 0x7f33a5931d48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083c48>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4083a88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083708>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4094f08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094888>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a40a0888>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a0088>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f488>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f748>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a6fb79c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408de88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a00c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40a0c48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a0848>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a4083dc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083508>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084c88>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a593f9c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f708>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4086188>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094248>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4081248>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a4081e48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4081588>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408e448>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a593f348>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f348>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593fd08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f1c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084f48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40847c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40835c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4096288>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096dc8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a408d208>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a408dc48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40817c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a0c48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4096a48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084f88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094d08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(TimeoutError(110, 'Connection timed out'),), <traceback object at 0x7f33a4094448>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(ConnectionRefusedError(111, 'Connection refused'),), <traceback object at 0x7f33a408d048>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408dfc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 504: 'Gateway Time-out'>, <traceback object at 0x7f33a4092f08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408eb08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408e348>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408e048>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081048>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593bbc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408eac8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f348>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593fe48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083ec8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4084188>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a40842c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408d888>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a5931f08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a59319c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4092fc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40966c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408ac08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40946c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a0b48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'View not found [name, type, prefix]: category, jpg, contentView'>, <traceback object at 0x7f33a593b808>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593bac8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086088>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a595e948>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a0688>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084b48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4092ec8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081588>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 500: 'Layout common/default not found.'>, <traceback object at 0x7f33a4096f08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593fdc8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a408d208>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4099648>)\n",
      "Unexpected error: (<class 'UnicodeEncodeError'>, UnicodeEncodeError('ascii', 'GET /wikipedia/en/7/7d/Yellowfin_tuna_at_the_Achiotines_Laboratory_in_Pedasí,_Panama.jpg HTTP/1.1', 75, 76, 'ordinal not in range(128)'), <traceback object at 0x7f33a4096748>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084d08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084208>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a40a0888>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40923c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593fac8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408a988>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4094708>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409f748>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a0448>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40818c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593b188>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 500: 'Internal Server Error'>, <traceback object at 0x7f33a409ff08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409f888>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40a0d88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a40a0a48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408af08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4099288>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094e88>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4099948>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a596f848>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a40a0cc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Object Not Found'>, <traceback object at 0x7f33a408d948>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4083f08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40a0388>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40a0e48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408d1c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409f248>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 504: 'Gateway Timeout'>, <traceback object at 0x7f33a409f6c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094f48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40966c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408e9c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408eec8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 500: 'Internal Server Error'>, <traceback object at 0x7f33a408eec8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408db48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409cb88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593fd08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40941c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4099188>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a409f288>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4092f88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081b48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4081f88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084208>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(TimeoutError(110, 'Connection timed out'),), <traceback object at 0x7f33a4084648>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f848>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086408>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408ac08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408ad88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a5974988>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a408d508>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084408>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4092e48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408a348>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a408a1c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40865c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a593fb08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409f948>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083f48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4094688>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094d48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f208>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4092e08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4084848>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084788>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40868c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a40865c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086588>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a593b8c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084dc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4084fc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f908>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593f9c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4086b48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a5931788>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a5931f08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40927c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4092e48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408a888>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4094488>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094048>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094608>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083608>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409f648>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(TimeoutError(110, 'Connection timed out'),), <traceback object at 0x7f33a409fcc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4086b48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a409c588>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4081f08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4081788>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4094388>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593f688>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a593f0c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4096b88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084808>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a408db88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408d148>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408e188>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408aa48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409cec8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a6217088>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a593f508>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4092a48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083948>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4083508>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a4083408>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593bf08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408d448>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409fb08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a409fc88>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-3, 'Temporary failure in name resolution'),), <traceback object at 0x7f33a4092248>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409c748>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a409cd48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094248>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40861c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a593f9c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(TimeoutError(110, 'Connection timed out'),), <traceback object at 0x7f33a593bcc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a408a348>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4081888>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a40811c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a4086648>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40940c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40949c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Object Not Found'>, <traceback object at 0x7f33a409cbc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 503: 'Service Unavailable'>, <traceback object at 0x7f33a408d588>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a409c688>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a59569c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a409f808>)\n",
      "Unexpected error: (<class 'ConnectionResetError'>, ConnectionResetError(104, 'Connection reset by peer'), <traceback object at 0x7f33a4081c08>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a40814c8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4094ac8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a4092148>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a40817c8>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(TimeoutError(110, 'Connection timed out'),), <traceback object at 0x7f33a408ae48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096fc8>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408e988>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4099c48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 403: 'Forbidden'>, <traceback object at 0x7f33a409cf48>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4096cc8>)\n",
      "Unexpected error: (<class 'ConnectionResetError'>, ConnectionResetError(104, 'Connection reset by peer'), <traceback object at 0x7f33a4096f88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a408dd08>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084e88>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4084148>)\n",
      "Unexpected error: (<class 'urllib.error.URLError'>, URLError(gaierror(-2, 'Name or service not known'),), <traceback object at 0x7f33a408d208>)\n",
      "Unexpected error: (<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f33a4081f08>)\n"
     ]
    }
   ],
   "source": [
    "for foldername in glob.glob('./*'):\n",
    "    for filename in glob.glob(foldername + '/*'):\n",
    "        f = open(filename, 'r')\n",
    "        for url in f:\n",
    "            try:\n",
    "                pic = open(foldername + '/' + url.split('/')[-1][:-1],'wb')\n",
    "                pic.write(urllib.request.urlopen(url).read())\n",
    "                pic.close()\n",
    "            except:\n",
    "                print(\"Unexpected error:\", sys.exc_info())\n",
    "        f.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import Image\n",
    "import os\n",
    "\n",
    "for foldername in glob.glob('./*'):\n",
    "    for filename in glob.glob(foldername + '/*'):\n",
    "        print(filename)\n",
    "        break\n",
    "        #try:\n",
    "        #    Image.open(filename)\n",
    "        #except OSError:\n",
    "        #    os.remove(filename)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
